services:
  app:
    build: .
    image: mvnaip
    container_name: mvnaip_app
    env_file: .env

    # Run your main script
    command: ["python", "src/main.py"]

    # Mount source files for live development
    volumes:
      - ./src:/app/src
      - ./src/logs:/app/src/logs